### ISSUE TITLE
get_form_list is bypassed

### ISSUE THREAD

**Issue by nahuelange** [jazzband/django-formtools#168] opened 2020-06-04 13:36 UTC
Hi,

I'm trying to implement conditionnal steps in my WizardView, using get_form_list to return the needed list of steps.
When I do this, formtools raises an exception trying to access a step in the form_list class attribute.
Line 409 of file `formtools/wizard/views.py`:

``` 
form_class = self.form_list[step] …
```

Don't the get_form_list method should be called everytime formtools needs the form_list instead of accessing the property?

**Comment by nahuelange** [comment] 2020-06-04 14:11
In my case i must use condition_dict, but the problem about get_form_list still is a question.

**Comment by spapas** [comment] 2021-03-12 17:24
Please could somebody give some love to this issue? You just need to change the the line `form_class = self.form_list[step]` of the `get_form` method to `form_class = self.get_form_list()[step]` to fix it. 

It would be really useful to be able to fully configure the list of forms of my wizard. Using the `condition_dict` is not as powerful as being able to completely redefine the list of the forms.

**Comment by martey** [comment] 2021-05-08 02:42
This looks like a duplicate of #62, which hasn't been merged because it doesn't include automated tests.

**Closed** 2022-03-02 18:43 UTC

**Comment by violuke** [comment] 2022-10-19 07:56
This change has caused a lot of people a problem, see #220, can this be reverted?
